models.py
from app import db
from datetime import datetime
import re


def slugify(title_item):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', title_item)


recipe_tags = db.Table('recipe_tags',
                       db.Column('recipe_id',
                                 db.Integer,
                                 db.ForeignKey('recipe.id')
                                 ),
                       db.Column('tag_id',
                                 db.Integer,
                                 db.ForeignKey('tag.id')
                                 ),
                       )


class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(40), unique=True)
    text = db.Column(db.Text)
    published = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        super(Recipe, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=recipe_tags, backref=db.backref('recipes', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title).lower()

    def __repr__(self):
        return f'<Recipe id:{self.id}, ' \
               f'title: {self.title},' \
               f'slug: {self.slug}, ' \
               f'text:" {self.text}", ' \
               f'published: {self.published}.>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag id:{self.id}, name:{self.name}>'

forms.py
from wtforms import Form, StringField, TextAreaField

class RecipeForm(Form):
    title = StringField('title')
    text = TextAreaField('text')

app.py
from flask import Flask, render_template
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import MigrateCommand, Migrate
from flask_script import Manager


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


@app.route('/', endpoint='index')
def index():
    return render_template('/index.html')

blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Recipe, Tag
from forms import RecipeForm
from app import db
import logging

recipes = Blueprint('recipes', __name__)


@recipes.route('/edit', methods=['POST', 'GET'])
def edit_recipe():
    if request.method == 'POST':
        title = request.form['title']
        text = request.form['text']

        try:
            recipe = Recipe(title=title, text=text)
            if recipe.title == '' or recipe.text == '':
                return redirect(url_for('recipes.edit_recipe'))
            else:
                db.session.add(recipe)
                db.session.commit()
        except:
            logging.basicConfig(filename="Error.log", level=logging.INFO)

        return redirect(url_for('recipes.index'))
    form = RecipeForm()
    return render_template('recipes/edit_recipe.html', form=form)


@recipes.route('/')
def index():
    q = request.args.get('q', '')

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if q != '':
        recipes_posts = Recipe.query.filter(Recipe.title.contains(q) | Recipe.text.contains(q))
    else:
        recipes_posts = Recipe.query.order_by(Recipe.published.desc())

    pages = recipes_posts.paginate(page=page, per_page=12)

    return render_template('recipes/index.html', recipes_posts=recipes_posts, pages=pages)


@recipes.route('/<slug>')
def recipe_detail(slug):
    if Recipe.query.filter(Recipe.slug == slug).first():
        recipe_post = Recipe.query.filter(Recipe.slug == slug).first()
        tags = recipe_post.tags
        return render_template('recipes/recipe_detail.html', recipe_post=recipe_post, tags=tags)
    else:
        logging.basicConfig(filename="Error_recipe.log", level=logging.INFO)
        return render_template('404/index.html')


@recipes.route('/tag/<slug>')
def tag_detail(slug):
    if Tag.query.filter(Tag.slug == slug).first():
        tag = Tag.query.filter(Tag.slug == slug).first()
        recipe_items = tag.recipes
        return render_template('recipes/tag_detail.html', tag=tag, recipes=recipe_items)
    else:
        logging.basicConfig(filename="Error_tag.log", level=logging.INFO)
        return render_template('404/index.html')


@recipes.route('/tags')
def all_tags():
    tag_names = Tag.query.all()
    return render_template('recipes/all_tags.html', tag_names=tag_names)

main.py
from app import app, db
from blueprint import recipes

app.register_blueprint(recipes, url_prefix='/recipes')

if __name__ == '__main__':
    db.create_all()
    app.run()

templates/404/index.html
{% extends 'base.html' %}

{% block title%}
404 title
{% endblock %}

{% block content %}
<center>Страница отсутствует <br>
Вы будете перенаправлены на страницу Рецептов.</center>

<meta http-equiv="refresh" content="5; {{ url_for('recipes.index')}}">
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="/static/css/main.css">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
                integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"></script>
        <title>
            {% block title%}
            Base title
            {% endblock%} | Flask App
        </title>
    </head>
    <body>
        <div class="header">
            <div class="container">
                <h1>
                    <a href="{{ url_for('index')}}">CookBook</a>
                </h1>
                <p class="project-name">Блог кулинара</p>
                <nav class="navbar navbar-expand-lg">
                    <ul class="navbar-nav mr-auto">
                        {% block navbar%}
                        <li class="nav-item active"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
                        <li class="nav-item"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>
                        {% endblock%}
                    </ul>
                    <form class="form-inline my-2 my-lg-0" method="GET">

                        <input class="form-control mr-sm-2"
                               type="search"
                               placeholder="ваш запрос"
                               aria-label="Search"
                               name="q"
                               value="{{ request.args.get('q', '') }}">
                        <button class="btn btn-search my-2 my-sm-0" type="submit">Поиск</button>
                    </form>
                </nav>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="container">
                    <div class="row row-cols-12">
                        <div class="col-9">
                            <div class="w-100"></div>

                            {% block content %}
                            <div class="margin-8"></div>
                                <h2>Рецепты</h2>
                                <div class="margin-8"></div>
                                {% for recipes in recipes_posts %}
                                <div class="card" style="width: 12rem;">
                                    <img src="/static/img/png/image.png" class="card-img-top img-thumbnail" alt="{{ recipes.title }}">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ recipes.title }}</h5>
                                        <a href="{{ url_for('recipes.recipe_detail', slug=recipes.slug)}}" class="btn btn-primary" target="_blank">К рецепту</a>
                                    </div>
                                </div>
                                {% endfor%}

                                {% endblock %}

                            </div>

                            <div class="col-3">
                                <div class="mar-pad-25"></div>
                                <form>
                                    <label for="exampleInputEmail1"><h4>Форма входа:</h4></label>
                                    <div class="form-group">
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Логин">
                                        <small id="emailHelp" class="form-text text-muted">Пользовательское соглашение</small>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль">
                                    </div>
                                    <div class="form-group form-check">
                                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                        <label class="form-check-label" for="exampleCheck1">Сохранить на этом устройстве</label>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-enter">Вход</button>
                                </form>
                                <div class="mar-pad-50"></div>
                                <h4 class="card-title">Новости:</h4>
                                <h6 class="card-subtitle mb-2 text-muted">04.04.2020</h6>
                                <p class="card-text">Новый сервис wishlist для покупок</p>
                                <a href="#" class="card-link"> <b>Подробнее</b> </a>
                                <div class="margin-8"></div>


                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
            </div>
        </div>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title%}
Рецепты title
{% endblock %}

{% block content %}
<div class="margin-8"></div>
<div class="alert alert-danger" role="alert">
  <p>Страница в разработке. Перейдите, пожалуйста, по <a href="recipes/">ссылке в раздел Рецепты</a>
</p>
</div>


<div class="content">
    <div class="margin-8"></div>
    <div id="carouselTitlePage" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

            <div class="carousel-item  active">
                <img src="static/img/png/01.png" class="d-block w-100" alt="...">
            </div>

            <div class="carousel-item">
                <img src="static/img/png/02.png" class="d-block w-100" alt="...">
            </div>

            <div class="carousel-item">
                <img src="static/img/png/03.png" class="d-block w-100" alt="...">
            </div>

        </div>
        <a class="carousel-control-prev" href="#carouselTitlePage" role="button" data-slide="prev">
            <svg class="bi bi-chevron-compact-left"
                 width="2em"
                 height="2em"
                 viewBox="0 0 16 16"
                 fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg"
            >
                <path fill-rule="evenodd"
                      d="M9.224 1.553a.5.5 0
                      01.223.67L6.56 8l2.888
                      5.776a.5.5 0 11-.894.448l-3-6a.5.5 0
                      010-.448l3-6a.5.5 0 01.67-.223z" clip-rule="evenodd"
                />
            </svg>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselTitlePage" role="button" data-slide="next">
            <svg class="bi bi-chevron-compact-right"
                 width="2em"
                 height="2em"
                 viewBox="0 0 16 16"
                 fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg"
            >
                <path fill-rule="evenodd"
                      d="M6.776 1.553a.5.5 0
                      01.671.223l3 6a.5.5 0
                      010 .448l-3 6a.5.5 0
                      11-.894-.448L9.44 8
                      6.553 2.224a.5.5 0
                      01.223-.671z" clip-rule="evenodd"
                />
            </svg>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="margin-8"></div>

    <h2>Рецепты</h2>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #1">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #1 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #2">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #2 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #3">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #3 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #4">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #4 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
              </div>
              <div class="content">
                <div class="margin-8"></div>
                <h2>Популярные рецепты</h2>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #5">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #5 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #6">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #6 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #7">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #7 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>
                <div class="card" style="width: 12rem;">
                  <img src="static/img/png/image.png" class="card-img-top img-thumbnail" alt="Рецепт #8">
                  <div class="card-body">
                    <h5 class="card-title"> Рецепт #8 </h5>
                    <a href="recipe.html" class="btn btn-primary">К рецепту</a>
                  </div>
                </div>          </div>
              <div class="content">
                <div class="margin-8"></div>
                <a href="#"><h3>«ЛОЖЕЧНЫЙ» СУП: ОТ ТАКОЙ МИНИАТЮРНОЙ КРАСОТЫ ГЛАЗ НЕ ОТВЕСТИ!</h3></a>
                        <hr>
                        <p>Суп из мясного бульона с крошечными домашними пельменями с мясом. Почему «ложечный» суп? Потому что мастерство в данном случае ложкой оценивается: чем больше пельменей помещается в ложке, тем искуснее хозяйка.</p>

                        <a class="btn btn-primary" href="#" role="button">Читать</a>            <div class="margin-8"></div>
                <a href="#"><h3>«ЛОЖЕЧНЫЙ» СУП: ОТ ТАКОЙ МИНИАТЮРНОЙ КРАСОТЫ ГЛАЗ НЕ ОТВЕСТИ!</h3></a>
                        <hr>
                        <p>Суп из мясного бульона с крошечными домашними пельменями с мясом. Почему «ложечный» суп? Потому что мастерство в данном случае ложкой оценивается: чем больше пельменей помещается в ложке, тем искуснее хозяйка.</p>

                        <a class="btn btn-primary" href="#" role="button">Читать</a>            <div class="margin-8 clear"></div>
              </div>
                {% endblock %}

templates/news/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/recipes/all_tags.html
{% extends 'base.html' %}

{% block title%}

{% endblock %}

{% block navbar%}
<li class="nav-item"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
<li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
<li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
<li class="nav-item"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>
{% endblock%}

{% block content %}

<div class="margin-8"></div>

<h2>Список тегов:</h2>

<div class="margin-8"></div>

{% for tags in tag_names %}
<div class="card mb-5">
    <div class="card-body">
        <a href="{{url_for('recipes.tag_detail', slug=tags.slug)}}"
           class="btn btn-primary" target="_blank">{{ tags.name }}</a>
    </div>
</div>
{% endfor%}
{% endblock %}

templates/recipes/edit_recipe.html
{% extends 'base.html' %}

{% block title%}
Edit posts
{% endblock %}

{% block navbar%}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
<li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
                <li class="nav-item active"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>
{% endblock%}

{% block content %}
<div class="margin-8"></div>

<div class="col-6">
    <form action="{{url_for('recipes.edit_recipe')}}" method="POST">

        <div class="margin-8"></div>
        {% for field in form %}

        <div class="form-group">
            {{field.label(class='control-label')}}
            {{field(class='form-control')}}
        </div>

        {% endfor %}
        <button class="btn btn-primary" type="submit">Сохранить</button>

    </form>
</div>
{% endblock %}

templates/recipes/index.html
{% extends 'base.html' %}

{% block title%}
Recipe title
{% endblock %}

{% block navbar%}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
                <li class="nav-item"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>
{% endblock%}

{% block content %}
<div class="margin-8"></div>

<h2>Рецепты</h2>


<div class="nav">
    <nav>
      <ul class="pagination justify-content-center">
          <li {% if not pages.has_prev %} class="page-item disabled" {% endif %} >
              <a class="page-link" href="./?page={{pages.prev_num}}" tabindex="-1">&laquo;</a>
          </li>
          {% for page in pages.iter_pages() %}
          <li {% if page == pages.page%} class="page-item active" {% endif%} >
              <a class="page-link" href="./?page={{page}}">{{page}}</a>
          </li>
          {% endfor%}
          <li {% if not pages.has_next %} class="page-item disabled" {% endif %} >
              <a class="page-link" href="./?page={{pages.next_num}}">&raquo;</a>
          </li>
      </ul>
    </nav>
</div>

<div class="margin-8"></div>
{% for recipes in pages.items %}

    <div class="card mb-5" style="width: 12rem;">
        <img src="/static/img/png/image.png" class="card-img-top img-thumbnail" alt="{{ recipes.title }}">
        <div class="card-body">
            <h5 class="card-title">{{ recipes.title }}</h5>
            <a href="{{ url_for('recipes.recipe_detail', slug=recipes.slug)}}" class="btn btn-primary" target="_blank">К рецепту</a>
        </div>
    </div>

{% endfor%}


{% endblock %}

templates/recipes/recipe_detail.html
{% extends 'base.html' %}

{% block title%}
{{ recipe_post.title }}
{% endblock %}

{% block navbar%}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
                <li class="nav-item"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>

{% endblock%}


{% block content %}
<div class="margin-8"></div>


<h2>{{ recipe_post.title }}</h2>

<div class="tags">
    {% for tag in tags %}
    <h5>
    <a href="{{url_for('recipes.tag_detail', slug=tag.slug)}}">
        <span class="badge badge-primary">{{ tag.name }}</span>
    </a></h5>
    {% endfor %}
</div>
<p>{{ recipe_post.text }}</p>






{% endblock %}

templates/recipes/tag_detail.html
{% extends 'base.html' %}

{% block title%}
{{ tag.name }} recipes
{% endblock %}

{% block navbar%}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('index')}}">Главная</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('recipes.index')}}">Рецепты</a></li>
                <li class="nav-item"><a class="nav-link" href="{{url_for('recipes.all_tags')}}">Все теги</a></li>
                <li class="nav-item"><a class="nav-link"  href="{{ url_for('recipes.edit_recipe') }}">Добавить новый пост</a></li>
{% endblock%}

{% block content %}

<div class="margin-8"></div>

<h2>Рецепты с тегом "{{ tag.name}}":</h2>

<div class="margin-8"></div>

{% for recipe in recipes %}

<div class="card" style="width: 12rem;">

    <img src="/static/img/png/image.png" class="card-img-top img-thumbnail" alt="{{ recipe.title }}">
    <div class="card-body">
        <h5 class="card-title">{{ recipe.title }}</h5>
        <a href="{{ url_for('recipes.recipe_detail', slug=recipe.slug)}}" class="btn btn-primary" target="_blank">К рецепту</a>
    </div>
</div>
{% endfor%}

{% endblock %}